# columns: date, state, fips, cases, deaths
STATES_FILENAME = 'nytdata/us-states.csv'
# columns: date, county, state, fips, cases, deaths
COUNTIES_FILENAME = 'nytdata/us-counties.csv'
# columns: date, cases, deaths
US_FILENAME = 'nytdata/us.csv'

states_dict = {
    "Washington": [],
    "Illinois": [],
    "California": [],
    "Arizona": [],
    "Massachusetts": [],
    "Wisconsin": [],
    "Texas": [],
    "Nebraska": [],
    "Utah": [],
    "Oregon": [],
    "Florida": [],
    "New York": [],
    "Rhode Island": [],
    "Georgia": [],
    "New Hampshire": [],
    "North Carolina": [],
    "New Jersey": [],
    "Colorado": [],
    "Maryland": [],
    "Nevada": [],
    "Tennessee": [],
    "Hawaii": [],
    "Indiana": [],
    "Kentucky": [],
    "Minnesota": [],
    "Oklahoma": [],
    "Pennsylvania": [],
    "South Carolina": [],
    "District of Columbia": [],
    "Kansas": [],
    "Missouri": [],
    "Vermont": [],
    "Virginia": [],
    "Connecticut": [],
    "Iowa": [],
    "Louisiana": [],
    "Ohio": [],
    "Michigan": [],
    "South Dakota": [],
    "Arkansas": [],
    "Delaware": [],
    "Mississippi": [],
    "New Mexico": [],
    "North Dakota": [],
    "Wyoming": [],
    "Alaska": [],
    "Maine": [],
    "Alabama": [],
    "Idaho": [],
    "Montana": [],
    "Puerto Rico": [],
    "Virgin Islands": [],
    "Guam": [],
    "West Virginia": [],
    "Northern Mariana Islands": []
}